"""Public API surface: DTOs, parameter specs, validation, typed errors."""
from __future__ import annotations

from .dto import (
    PARAMETER_KINDS,
    Assignment,
    ExpansionReceipt,
    ParameterSpec,
    Target,
    Template,
    TemplateRevision,
)
from .errors import (
    CapabilityUnknownError,
    CasConflictError,
    CommandTemplateError,
    ContentMissingError,
    ContributorGoneError,
    IdempotencyConflictError,
    InvalidDocumentError,
    InvalidIdentifierError,
    NameConflictError,
    NativeUnsupportedError,
    OutputLimitError,
    ParameterInvalidError,
    ProjectionRefusedError,
    RevisionUnapprovedError,
    StalePreviewError,
    UnauthorizedTargetError,
    UnknownParameterError,
    UnresolvedParameterError,
)
from .schema import (
    MAX_BODY_BYTES,
    MAX_RENDERED_BYTES,
    normalize_body,
    validate_body,
    validate_namespaced_route,
    validate_param_name,
    validate_slug,
    validate_template_id,
)

__all__ = [
    "PARAMETER_KINDS",
    "Assignment",
    "ExpansionReceipt",
    "ParameterSpec",
    "Target",
    "Template",
    "TemplateRevision",
    "CommandTemplateError",
    "InvalidIdentifierError",
    "InvalidDocumentError",
    "UnauthorizedTargetError",
    "ContentMissingError",
    "RevisionUnapprovedError",
    "ParameterInvalidError",
    "UnknownParameterError",
    "UnresolvedParameterError",
    "OutputLimitError",
    "NameConflictError",
    "StalePreviewError",
    "CasConflictError",
    "IdempotencyConflictError",
    "ContributorGoneError",
    "NativeUnsupportedError",
    "CapabilityUnknownError",
    "ProjectionRefusedError",
    "MAX_BODY_BYTES",
    "MAX_RENDERED_BYTES",
    "normalize_body",
    "validate_body",
    "validate_namespaced_route",
    "validate_param_name",
    "validate_slug",
    "validate_template_id",
]
