"""T09 scan inventory: the legacy truth is reported as found, nothing fixed.

The sample is generated by the REAL legacy pieces (McpAssetStore.install +
AssetRecords.publish/bind on a migrated pacthold Database, see legacy_sample.py),
so every expectation below is a byte-level fact of that pipeline.
"""
from __future__ import annotations

from legacy_sample import build_digest_mismatch_dataset, build_legacy_dataset
from ordessa_server_compat.assets import mcp as legacy

from backend.migration import scan_legacy


def _assets_by_id(scan):
    return {asset["asset_id"]: asset for asset in scan["assets"]}


def test_scan_lists_every_mcp_asset_row_and_skips_other_kinds(tmp_path):
    dataset = build_legacy_dataset(tmp_path)
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    assert sorted(_assets_by_id(scan)) == ["env-ref-srv", "fs-local", "remote-weather"]
    assert scan["profiles"] == ["p-alpha", "p-beta"]
    # 5 mcp bindings in the sample; every row reported with its joined digest
    assert len(scan["bindings"]) == len(dataset.records.bindings("p-alpha")) \
        + len(dataset.records.bindings("p-beta"))
    assert scan["refusals"]["digest-mismatch"] == []
    assert scan["refusals"]["dangling-binding"] == []


def test_digest_column_is_cross_checked_against_legacy_definition_digest(tmp_path):
    dataset = build_legacy_dataset(tmp_path)
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    fs_local = _assets_by_id(scan)["fs-local"]
    rev1, rev2 = fs_local["revisions"]
    assert (rev1["revision"], rev1["status"]) == (1, "unattested")
    assert (rev2["revision"], rev2["status"]) == (2, "attested")
    # the file digests are what the legacy store itself computes (verify=True)
    legacy_store = legacy.McpAssetStore(dataset.assets_root)
    assert rev1["file_digest"] == dataset.facts["fs-local@1"]["digest"]
    assert rev2["file_digest"] == dataset.facts["fs-local@2"]["digest"]
    assert legacy_store.verify(asset_id="fs-local", revision=2,
                               expected_digest=fs_local["digest"])
    assert fs_local["status"] == "attested"


def test_binding_rows_carry_the_legacy_view_quirk_verbatim(tmp_path):
    """bindings to fs-local@1 JOIN the row digest of revision 2 — the old
    ``AssetRecords.bindings`` output does that, and the scan mirrors it."""
    dataset = build_legacy_dataset(tmp_path)
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    for binding in scan["bindings"]:
        legacy_row = next(
            row for row in dataset.records.bindings(binding["profile_id"])
            if row["assetId"] == binding["asset_id"])
        assert (binding["digest"], binding["revision"], binding["enabled"],
                binding["name"]) == (legacy_row["digest"], legacy_row["revision"],
                                     legacy_row["enabled"], legacy_row["name"])
        assert binding["file_status"] == "present"
    old = [b for b in scan["bindings"] if b["asset_id"] == "fs-local"]
    assert old and all(b["revision"] == 1 and b["file_status"] == "present" for b in old)
    assert old[0]["digest"] == dataset.facts["fs-local@2"]["digest"]


def test_digest_column_mismatch_is_listed_not_repaired(tmp_path):
    dataset = build_legacy_dataset(tmp_path)
    before = (dataset.assets_root / "mcp" / "remote-weather" / "1" / "server.json"
              ).read_bytes()
    dataset.mutate_rows("UPDATE server_assets SET digest=? WHERE id=?",
                        ("sha256:" + "0" * 64, "remote-weather"))
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    mismatch = scan["refusals"]["digest-mismatch"]
    assert [item["asset_id"] for item in mismatch] == ["remote-weather"]
    assert mismatch[0]["reason"] == "digest-column-differs-from-file"
    assert mismatch[0]["column_digest"] == "sha256:" + "0" * 64
    assert mismatch[0]["file_digest"] == dataset.facts["remote-weather@1"]["digest"]
    assert _assets_by_id(scan)["remote-weather"]["status"] == "digest-mismatch"
    # the scan reads only: the revision file is byte-unchanged afterwards
    assert (dataset.assets_root / "mcp" / "remote-weather" / "1" / "server.json"
            ).read_bytes() == before


def test_missing_bound_revision_file_is_listed_as_dangling(tmp_path):
    dataset = build_legacy_dataset(tmp_path)
    (dataset.assets_root / "mcp" / "fs-local" / "1" / "server.json").unlink()
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    assert [item["asset_id"] for item in scan["refusals"]["dangling-binding"]] \
        == ["fs-local", "fs-local"]  # p-alpha and p-beta both reference rev1
    assert all(item["reason"] == "revision-file-missing-or-unreadable"
               for item in scan["refusals"]["dangling-binding"])
    # asset itself still attested through revision 2 (digest check is per row)
    assert _assets_by_id(scan)["fs-local"]["status"] == "attested"


def test_digest_mismatch_dataset_helper_matches_manual_surgery(tmp_path):
    dataset = build_digest_mismatch_dataset(tmp_path)
    scan = scan_legacy(dataset.db_path, dataset.assets_root)
    assert [item["asset_id"] for item in scan["refusals"]["digest-mismatch"]] \
        == ["remote-weather"]
