// @ordessa/ui — directly-importable React foundations (C8).
// This barrel is pure: importing it registers nothing, injects no styles,
// touches no DOM/global (F05). Styles ship as the separate explicit entry
// `@ordessa/ui/styles.css`, loaded by the product assembly, never from JS.
export {
  Card,
  CardRoot,
  CardHeader,
  CardTitle,
  CardDescription,
  CardActions,
  CardBody,
  CardFooter,
  Panel,
  PanelRoot,
  PanelHeader,
  PanelTitle,
  PanelActions,
  PanelBody,
  PanelFooter,
  type CardVariant,
  type CardRootProps,
  type CardSectionProps,
  type PanelRootProps,
} from './containers'
export {
  Stack,
  Inline,
  Toolbar,
  ScrollArea,
  Separator,
  type UiSpacing,
  type UiAlign,
  type UiJustify,
  type StackProps,
  type InlineProps,
  type ToolbarProps,
  type ScrollAreaProps,
  type SeparatorProps,
} from './layout'
export {
  Button,
  IconButton,
  Input,
  Textarea,
  Select,
  Checkbox,
  type ButtonVariant,
  type ControlSize,
  type ButtonProps,
  type IconButtonProps,
  type InputProps,
  type TextareaProps,
  type SelectProps,
  type CheckboxProps,
} from './controls'
export {
  Field,
  FieldRoot,
  FieldLabel,
  FieldControl,
  FieldDescription,
  FieldError,
  type FieldPart,
  type FieldControlState,
  type FieldRootProps,
  type FieldControlProps,
} from './field'
export {
  Badge,
  Notice,
  EmptyState,
  type UiTone,
  type BadgeProps,
  type NoticeProps,
  type EmptyStateProps,
} from './feedback'
