"""Ordessa native subagent definitions — this domain's public surface.

Only the pure definition store lives here: content, immutable revisions,
provenance approval, CAS and archive. Running a subagent, grant edges and
native file writes belong to Harness/runtime (spec FR12).
"""
from __future__ import annotations

from .decoder import (
    check_credential_free,
    check_text,
    decode_definition,
    decode_import_document,
    decode_revision,
    has_credential_shape,
    is_compilable,
    is_path_shaped,
    validate_definition,
    validate_revision,
)
from .digest import bytes_digest, canonical_digest, is_digest, revision_digest
from .dto import (
    ORIGIN_SCOPES,
    SOURCE_ORIGINS,
    AgentDefinition,
    DefinitionRevision,
    ImportFile,
    ImportPlan,
    ImportPreview,
    McpRef,
    ModelRef,
    SkillRef,
    SourceApproval,
    ToolRef,
    new_definition_id,
    new_preview_id,
)
from .errors import (
    ADAPTER_MISSING,
    ASSIGNMENT_CONFLICT,
    DEFINITION_INVALID,
    ERROR_CODES,
    LOAD_UNVERIFIED,
    NATIVE_DISCOVERY_UNCONTROLLED,
    NATIVE_ENTRY_UNAVAILABLE,
    NATIVE_NAME_CONFLICT,
    NATIVE_VERSION_UNKNOWN,
    OPERATION_UNKNOWN,
    PERMISSION_EXCEEDS_CEILING,
    PROVIDER_BUSY,
    REFERENCE_UNRESOLVED,
    REVISION_STALE,
    TARGET_CONFLICT,
    DomainError,
    refused,
)
from .service import Authority, DefinitionService
from .store import DefinitionStore

__all__ = [
    "ADAPTER_MISSING",
    "ASSIGNMENT_CONFLICT",
    "AgentDefinition",
    "Authority",
    "DEFINITION_INVALID",
    "ERROR_CODES",
    "DefinitionRevision",
    "DefinitionService",
    "DefinitionStore",
    "DomainError",
    "ImportFile",
    "ImportPlan",
    "ImportPreview",
    "LOAD_UNVERIFIED",
    "McpRef",
    "ModelRef",
    "NATIVE_DISCOVERY_UNCONTROLLED",
    "NATIVE_ENTRY_UNAVAILABLE",
    "NATIVE_NAME_CONFLICT",
    "NATIVE_VERSION_UNKNOWN",
    "OPERATION_UNKNOWN",
    "ORIGIN_SCOPES",
    "PERMISSION_EXCEEDS_CEILING",
    "PROVIDER_BUSY",
    "REFERENCE_UNRESOLVED",
    "REVISION_STALE",
    "SOURCE_ORIGINS",
    "SkillRef",
    "SourceApproval",
    "TARGET_CONFLICT",
    "ToolRef",
    "bytes_digest",
    "canonical_digest",
    "check_credential_free",
    "check_text",
    "decode_definition",
    "decode_import_document",
    "decode_revision",
    "has_credential_shape",
    "is_compilable",
    "is_digest",
    "is_path_shaped",
    "new_definition_id",
    "new_preview_id",
    "refused",
    "revision_digest",
    "validate_definition",
    "validate_revision",
]
